// swift-tools-version:5.9
import PackageDescription

// Qdrant Edge, the in-process vector search engine OneShot matches photos with.
//
// Both inputs are generated by `Scripts/build-qdrant-edge.sh` and git-ignored: the
// XCFramework is several hundred MB of static library, and the Swift binding is
// UniFFI output regenerated from the same pinned commit. Run that script once
// before opening the project.
//
// The binding compiles here, in Swift 5 language mode, rather than inside the app
// target: UniFFI's generated code predates Swift 6 strict concurrency, and keeping
// it in its own module stops it from setting the app's language mode.
let package = Package(
    name: "QdrantEdge",
    platforms: [.iOS("26.0")],
    products: [
        .library(name: "QdrantEdge", targets: ["QdrantEdge"]),
    ],
    targets: [
        .target(
            name: "QdrantEdge",
            dependencies: ["qdrant_edge_ffiFFI"],
            path: "Sources/QdrantEdge"
        ),
        .binaryTarget(
            name: "qdrant_edge_ffiFFI",
            path: "QdrantEdge.xcframework"
        ),
    ]
)
